export const MEETING_MODE = {
  /** 正常模式 */
  VIDEO: 'VIDEO',
  /** 共享屏幕模式 */
  SHARE: 'SHARE',
  /** 互动白板模式 */
  WHITE_BOARD: 'WHITE_BOARD',
};

export const EXIT_REASON = {
  NETWORK_ERROR: 'NETWORK_ERROR',
  KICK_OUT: 'KICK_OUT',
  FREE_BENEFIT_EXPIRED: 'FREE_BENEFIT_EXPIRED',
  PAY_BENEFIR_EXPIRED: 'PAY_BENEFIR_EXPIRED',
  VMR_END_MEETING: 'VMR_END_MEETING',
};

export const MEETING_EVENT_MAP = {
  MEMBER_UPDATE: 'MEMBER_UPDATE',
  MEMBER_QUIT: 'MEMBER_QUIT',
  MEMBER_JOIN: 'MEMBER_JOIN',
  MUTE_ALL: 'MUTE_ALL',
  REQUEST_TURN_ON_CAMERA: 'REQUEST_TURN_ON_CAMERA',
  REQUEST_TURN_ON_MICROPHONE: 'REQUEST_TURN_ON_MICROPHONE',
  MEETING_INFO_UPDATE: 'MEETING_INFO_UPDATE',
  MODE_UPDATE: 'MODE_UPDATE',
  MEETING_END: 'MEETING_END',
  KICK_OUT: 'KICK_OUT',
  DISCONNECT: 'DISCONNECT',
  MAIN_VENUE_UPDATE: 'MAIN_VENUE_UPDATE',
  UPDATE_MEMBER_ROLE: 'UPDATE_MEMBER_ROLE',
  ACTIVE_MEMBER_UPDATE: 'ACTIVE_MEMBER_UPDATE',
  OPTIONS_CHANGED: 'OPTIONS_CHANGED',
};

export const EROLE_TYPE = {
  ORGANIZER: 1,
  HOST: 2,
  MEMBER: 3,
};

export const ROLE_TYPE = {
  1: 'ORGANIZER',
  2: 'HOST',
  3: 'MEMBER',
};

export const EROLE = {
  ORGANIZER: 'ORGANIZER',
  HOST: 'HOST',
  MEMBER: 'MEMBER',
};

export const END_MEETING_TYPE = {
  /** 免费会议已到期 */
  FREE_BENEFIT_EXPIRED: 4,
  /** 付费会议已到期 */
  PAY_BENEFIR_EXPIRED: 5,
  /** 专属会议室的人开启了新的会议 */
  VMR_END_MEETING: 6,
};
